[package]
name = "neorofi"
version = "0.1.0"
edition = "2021"
authors = ["Igor Shegolev <igorsheg@gmail.com>"]
license = "GPL-3"


[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.2", features = ["derive"] }
dirs-next = "2.0.0"
rofi = "0.4.0"
walkdir = "2.5.0"
